### ISSUE TITLE
Precomputations for Ate Miller loop

### ISSUE THREAD

**Issue by UlrichHaboeck75** [HorizenOfficial/ginger-lib#39]
The present code of the Miller loop for the MNT4/6 Ate pairings uses the pre-computed values
- for $P=(x_P,y_P)$ from $G_1$:  $(x_P, y_P*twist^2)$, 
- for $Q=(x_Q,y_Q)$ from $G_2$: for each intermediate point R, $(y_R, \gamma, \gamma * x_R)$, where $\gamma$ is the slope in the base field F of the quadratic twist (i.e. F2 for MNT4, F3 for the MNT6).

Later, point evaluation of the Miller line (scaled by twist^2) in the embedding field $F_e = F[Y]/(Y^2-twist)$ is computed as
$$
(y_p - \lambda * x_p - d) * twist^2 = (y_p*twist^2 - (\gamma * twist * x_p - y_R - \gamma * x_R ) * Y),
$$
where the terms $\gamma'= \gamma * twist$, $d'= y_R - \gamma * x_R$ are (re-)computed for every single line, although they are independent of $P$.

Beside gathering the point evaluation code in a separate function (as done for the ZEXE sw6), I propose to define the pre-computed values for $Q$ as the two elements 
- $\gamma' := \gamma * twist$, and
- $d' = y_R - \gamma * x_R$

instead (for each Miller line), and reduce point evaluation to
$$
(y_p - \lambda * x_p - d) * twist^2 = (y_p * twist^2 - (\gamma' * x_p - d' ) * Y),
$$
saving two multiplications and one addition in the base field F of the quadratic twist.

**Comment by 95DDB** [comment]
Not needed anymore after #144
