### ISSUE TITLE
Optimizing deg-3 extension field gadgets

### ISSUE THREAD

**Issue by UlrichHaboeck75** [HorizenOfficial/ginger-lib#50]
Some code of the cubic extension field gadgets `Fp3Gadget` and `Fp6Gadget` as '3over2' can be optimized:
- the `inverse` gadget uses Karatsuba multiplication using 6 base field constraints instead of Toom-Cook's 5 constraints
- the `square` gadget uses Toom-Cook multiplication, but according to [Devigili, et al.,](https://www.iacr.org/cryptodb/data/paper.php?pubkey=21962) the Chung-Hasan asymmetric squaring formula (CH-SQR2) replaces 3 multiplications by squares ([Zexe replaced this piece of code today](https://github.com/scipr-lab/zexe/pull/174/files)).
- `mul_by_constant` uses for no reason Toom-Cook with more than 100 lines, although the naive multiplication yields the same result.

Some of these issues are described in more detail in the docu branch of the field gadgets, [PR of docu field gadgets](https://github.com/ZencashOfficial/ginger-lib/pull/49).

**Comment by 95DDB** [comment]
Done as part of #74.
