### ISSUE TITLE
NEqGadget implementation of extension field gadgets

### ISSUE THREAD

**Issue by UlrichHaboeck75** [HorizenOfficial/ginger-lib#51]
In all our extension fields gadgets, the 'not-equal' gadget `NEqGadget` as implemented enforces inequality of *all* components (=vector coordinates), and not of at least one.

Besides that this does not describe the 'canoncial' behaviour one would expect, it is necessary to evaluate the impact of using this stricter notion of inequality in other gadgets (e.g., for affine EC arithmetics, which need to compare against the 0 element, etc.).

**Update** 
The impact is surprisingly harmless. The AffineGadgets which use `enforce_not_equal` of field elements to implement the inequality gadget of points is only used at a single place of code by now (in the G2PreparedGadget of BLS12 pairings), which has no security impact.

*Still to prevent malicious impact I recommend to correct the extension field NEqGadgets to reflect the expected behaviour.*

**Comment by Pratyush** [comment]
Hmm this is more of a completeness issue: it rejects some valid assignments  (eg: where two unequal curve points have the same y-coordinate but different x-coordinates), but doesn't incorrectly allow equal elements to pass the check

**Comment by UlrichHaboeck75** [comment]
> Hmm this is more of a completeness issue: it rejects some valid assignments (eg: where two unequal curve points have the same y-coordinate but different x-coordinates), but doesn't incorrectly allow equal elements to pass the check

I agree, it's a bit exaggerated to label that one as security issue. 
However, due to a misleading name it might be naively applied in systems where such stricter non-equality in fact has non-negligible impact to the distribution of instances. 
Hence I'd opt for renaming it and implementing the complete non-equality (which comes with twice as many constraints, though).

**Comment by Pratyush** [comment]
FWIW, I've fixed this upstream in the master branch

**Comment by UlrichHaboeck75** [comment]
Cool, thank you!

**Comment by 95DDB** [comment]
Done as part of #74.
