### ISSUE TITLE
Updatable Poseidon Hash

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/ginger-lib#56]
To be able to not have to collect first all the inputs together and then passing them to poseidon, add the possibility to pass just one input at a time and keep the state in a separate structure. The state will be updated each time that the inputs collected so far are multiple of R or if the finalize method was called and something was still in the pending inputs.

**Comment by 95DDB** [comment]
Implemented in #69. We have now PoseidonHash and FieldBasedOptimizedMHT with a init()/update()/finalize() like API, designed to be efficient in memory and timings.
