### ISSUE TITLE
Documentation with example

### ISSUE THREAD

**Issue by Tails** [HorizenOfficial/ginger-lib#71]
This looks like a promising library, but how do you use it? 

- Can it be used as both R1CS frontend (compiling) and backend? 
- Or should the library be used from Rust itself based on R1CS primitives? Then,
- How does one perform a simple circuit generation and proving? Some example code like https://github.com/microsoft/Spartan would be helpful

**Comment by mauriziobinello** [comment]
Ginger-lib is a fork of Zexe, with a strong focus on Snark recursion. It's a complete library; you can use it to both define circuits, and to make and verify proofs, and more. It was built as part of the Horizen Sidechain system, so it's not meant be an introductory tool to the SNARK world; having said that, you can find example code, and in particular the proving systems (e.g. groth16) come with examples of recursion. As ginger-lib gets used and adopted, some example code will likely come also from the user community!
